/**
 * World Manufacturer Identifiers → [brand, group]. Declarative data (CLAUDE.md §13).
 * Focus on brands common in France. 3-char keys first, 2-char fallbacks.
 * Group ids match future manufacturer plugins: vag, renault, stellantis, toyota, ford, bmw,
 * mercedes, hyundai-kia, nissan, honda, mazda, volvo, fiat, other.
 * Source: ISO 3780 assignments as published by manufacturers / SAE WMI lists (public).
 */
export const WMI_TABLE: Record<string, readonly [string, string]> = {
  // VAG
  WVW: ['Volkswagen', 'vag'],
  WV1: ['Volkswagen Utilitaires', 'vag'],
  WV2: ['Volkswagen Utilitaires', 'vag'],
  WV3: ['Volkswagen Utilitaires', 'vag'],
  WVG: ['Volkswagen (SUV)', 'vag'],
  '1VW': ['Volkswagen (USA)', 'vag'],
  '3VW': ['Volkswagen (Mexique)', 'vag'],
  '9BW': ['Volkswagen (Brésil)', 'vag'],
  WAU: ['Audi', 'vag'],
  WA1: ['Audi (SUV)', 'vag'],
  WUA: ['Audi Sport', 'vag'],
  TRU: ['Audi (Hongrie)', 'vag'],
  TMB: ['Škoda', 'vag'],
  VSS: ['Seat / Cupra', 'vag'],
  VS6: ['Seat / Cupra', 'vag'],
  WP0: ['Porsche', 'vag'],
  WP1: ['Porsche (SUV)', 'vag'],
  // Renault group
  VF1: ['Renault', 'renault'],
  VF2: ['Renault', 'renault'],
  VF6: ['Renault Trucks', 'renault'],
  VF8: ['Renault (Matra/Alpine)', 'renault'],
  UU1: ['Dacia', 'renault'],
  UU3: ['Dacia', 'renault'],
  UU5: ['Dacia', 'renault'],
  UU6: ['Dacia', 'renault'],
  VGA: ['Alpine', 'renault'],
  KNM: ['Renault Samsung', 'renault'],
  // Stellantis (PSA + FCA + Opel)
  VF3: ['Peugeot', 'stellantis'],
  VR3: ['Peugeot', 'stellantis'],
  VF7: ['Citroën', 'stellantis'],
  VR7: ['Citroën', 'stellantis'],
  VR1: ['DS Automobiles', 'stellantis'],
  W0L: ['Opel', 'stellantis'],
  W0V: ['Opel', 'stellantis'],
  ZFA: ['Fiat', 'stellantis'],
  ZFC: ['Fiat Professional', 'stellantis'],
  ZAR: ['Alfa Romeo', 'stellantis'],
  ZLA: ['Lancia', 'stellantis'],
  ZAP: ['Piaggio', 'other'],
  '1C4': ['Jeep / Chrysler', 'stellantis'],
  '1J4': ['Jeep', 'stellantis'],
  '1C3': ['Chrysler', 'stellantis'],
  '1C6': ['Ram', 'stellantis'],
  '1B3': ['Dodge', 'stellantis'],
  '2C3': ['Chrysler (Canada)', 'stellantis'],
  // Toyota
  JTD: ['Toyota', 'toyota'],
  JTE: ['Toyota', 'toyota'],
  JTN: ['Toyota', 'toyota'],
  JTH: ['Lexus', 'toyota'],
  JTJ: ['Lexus', 'toyota'],
  SB1: ['Toyota (Royaume-Uni)', 'toyota'],
  NMT: ['Toyota (Turquie)', 'toyota'],
  VNK: ['Toyota (France)', 'toyota'],
  '4T1': ['Toyota (USA)', 'toyota'],
  '5TD': ['Toyota (USA)', 'toyota'],
  // Ford
  WF0: ['Ford (Allemagne)', 'ford'],
  WF1: ['Ford (Allemagne)', 'ford'],
  '1FA': ['Ford (USA)', 'ford'],
  '1FM': ['Ford (USA)', 'ford'],
  '1FT': ['Ford (USA)', 'ford'],
  '1LN': ['Lincoln', 'ford'],
  NM0: ['Ford (Turquie)', 'ford'],
  // BMW
  WBA: ['BMW', 'bmw'],
  WBS: ['BMW M', 'bmw'],
  WBX: ['BMW (SUV)', 'bmw'],
  WBY: ['BMW i', 'bmw'],
  WMW: ['Mini', 'bmw'],
  '5UX': ['BMW (USA)', 'bmw'],
  // Mercedes
  WDB: ['Mercedes-Benz', 'mercedes'],
  WDD: ['Mercedes-Benz', 'mercedes'],
  WDC: ['Mercedes-Benz (SUV)', 'mercedes'],
  WDF: ['Mercedes-Benz Utilitaires', 'mercedes'],
  W1K: ['Mercedes-Benz', 'mercedes'],
  W1N: ['Mercedes-Benz (SUV)', 'mercedes'],
  W1V: ['Mercedes-Benz Utilitaires', 'mercedes'],
  WME: ['Smart', 'mercedes'],
  VSA: ['Mercedes-Benz (Espagne)', 'mercedes'],
  // Hyundai / Kia
  KMH: ['Hyundai', 'hyundai-kia'],
  KMF: ['Hyundai Utilitaires', 'hyundai-kia'],
  TMA: ['Hyundai (Rép. tchèque)', 'hyundai-kia'],
  NLH: ['Hyundai (Turquie)', 'hyundai-kia'],
  KNA: ['Kia', 'hyundai-kia'],
  KND: ['Kia (SUV)', 'hyundai-kia'],
  U5Y: ['Kia (Slovaquie)', 'hyundai-kia'],
  U6Y: ['Kia (Slovaquie)', 'hyundai-kia'],
  // Nissan
  JN1: ['Nissan', 'nissan'],
  JN8: ['Nissan (SUV)', 'nissan'],
  SJN: ['Nissan (Royaume-Uni)', 'nissan'],
  VSK: ['Nissan (Espagne)', 'nissan'],
  VWA: ['Nissan (Espagne)', 'nissan'],
  // Honda
  JHM: ['Honda', 'honda'],
  JHL: ['Honda (SUV)', 'honda'],
  SHH: ['Honda (Royaume-Uni)', 'honda'],
  SHS: ['Honda (Royaume-Uni)', 'honda'],
  // Mazda
  JM1: ['Mazda', 'mazda'],
  JMZ: ['Mazda (Europe)', 'mazda'],
  // Volvo
  YV1: ['Volvo', 'volvo'],
  YV4: ['Volvo (SUV)', 'volvo'],
  LVY: ['Volvo (Chine)', 'volvo'],
  // Others common in France
  JSA: ['Suzuki', 'other'],
  TSM: ['Suzuki (Hongrie)', 'other'],
  JMB: ['Mitsubishi', 'other'],
  JF1: ['Subaru', 'other'],
  SAL: ['Land Rover', 'other'],
  SAJ: ['Jaguar', 'other'],
  LRW: ['Tesla (Chine)', 'other'],
  '5YJ': ['Tesla', 'other'],
  XP7: ['Tesla (Allemagne)', 'other'],
  LSJ: ['MG (SAIC)', 'other'],
  LJC: ['JAC', 'other'],
  LGX: ['BYD', 'other'],
}
